### ISSUE TITLE
Feature Request: Support use as a transform module

### ISSUE THREAD

**Issue by georgeedwards** [KnisterPeter/tscodeshift#19]
Thanks for an awesome project, should really help out what I am working on. I am looking for a drop in replacement for JSCode's transform module. FYI - [this](https://github.com/feathersjs/generator-feathers/blob/master/lib/transform.js) is the behaviour I am looking to replicate for TS.

I am more than happy to help contribute if required. Let me know what you think.

**Comment by KnisterPeter** [comment]
Thank you. I'm glad to help. :smile: 

From what I think it should already be possible. There may be APIs missing and `ts-emitter` - the underlying tool - is probably not up-to-date with typescript 2.5.
Pull requests are more than welcome.

**Comment by georgeedwards** [comment]
@KnisterPeter Great! OK, well I'll take a look under the hood. The way the cli tool we are working on, uses jscodeshift like this:

```
j.registerMethods({findDeclaration(name) {
    return this.findVariableDeclarators(name)
      .closest(j.VariableDeclaration);
  },})
```

if I redefine `j` as tscodeshift, then I get error:

> TypeError: j.registerMethods is not a function

But I'll take a look at it :)

**Comment by KnisterPeter** [comment]
You could have a look at the example transforms: https://github.com/KnisterPeter/tscodeshift/blob/master/src/transforms/mocha.ts
But as stated above, there maybe some APIs missing.
