### ISSUE TITLE
examples folder

### ISSUE THREAD

**Issue by brekk** [KnisterPeter/tscodeshift#22]
Hey @KnisterPeter,

I've been digging the latest version of `tscodeshift` a bunch, it's doing exactly what I want. 🎉 

I was wondering whether you think it would be valuable to have an examples / transforms folder where some simple / common recipes are layed out?

I wrote a very simple transformer to cut my teeth on this library, but I could've used some guidance instead of debugging. (and right now it fails hilariously on some files)

I'd be more than happy to help with this task if you think it'd be valuable. (Perhaps there's an alternative like publishing `tscodeshift-transformer-x` if you don't want to dirty up this repo with those examples.)

Please let me know.

Thanks!

**Comment by KnisterPeter** [comment]
> I was wondering whether you think it would be valuable to have an examples / transforms folder where some simple / common recipes are layed out?

The `src/transforms` folder is meant for examples and tests.

Any contribution is more than welcome. :+1: 
Feel free to open PRs as much as you like.
