### ISSUE TITLE
using createLiteral to populate as ts.createArrayLiteral() throw an error

### ISSUE THREAD

**Issue by lionelB** [KnisterPeter/tscodeshift#24]
using 
```js
ast.find(ts.SyntaxKind.PropertyDeclaration)
    .filter(p => p.name.text === '$inject')
    .get(node => node.initializer) 
    .replaceWith(() =>  ts.createArrayLiteral(props.map(prop => ts.createLiteral(prop))) 
    .toSource()
```

throw a `TypeError: Cannot read property 'getFullText' of undefined`

I'm trying to populate the $inject array with constructor parameters  like 
`static $inject:string[] = ['titi', 'toto'] `

```ts
import {  User } from './user';
export class TestClass { 
  static $inject:string[] = [] 

  constructor(
    private titi: User,
    private toto: User
  ) {}
}
```
here is the full transform file for reference
```ts
const ts = require('typescript')

exports.default = (file, api) => {
  const t = api.tscodeshift;
  const ast = t(file.source); 

  const props =  []

  ast.find(ts.SyntaxKind.Parameter)
    .filter( p => p.parent.kind === ts.SyntaxKind.Constructor) 
    .forEach(p => props.push(p.name))

  ast.find(ts.SyntaxKind.PropertyDeclaration)
    .filter(p => p.name.text === '$inject')
    .get(node => node.initializer) 
    .replaceWith(() =>  ts.createArrayLiteral(prop => ts.createLiteral(prop)))
    
  return ast.toSource() 
} 
```

**Comment by KnisterPeter** [comment]
Without looking into the details I would say it looks like a bug.

**Comment by lionelB** [comment]
@KnisterPeter I've started digging into tscodeshift Collection.ts code to see where the error come from. I try some stuff like replacing the identifier with some assignment like you do in the mocha transform example and it works, but as soon as I try to create a literral, it fail :/

**Comment by KnisterPeter** [comment]
Maybe there is an error in the underlying `ts-emitter` library regarding literals. That is possible.

**Comment by lionelB** [comment]
from what I understand, 
ts-emiter try to access to `.newText`property but since it doesn't exist, it try to read literal from source file. wich fail 

https://github.com/KnisterPeter/ts-emitter/blob/master/src/emitter.ts#L2580-L2582

-edit-
```ts
.replaceWith((node) =>  { 
  const foo = ts.createLiteral('foo')
  foo.newText = '"foo"'
  return ts.createArrayLiteral(
    [foo]
  ) 
}) 
```

this works !

**Comment by KnisterPeter** [comment]
Nice debugging. I'll have a look at that and will update the `ts-emitter` api/handling for this.
Could you live with your workaround for now?

**Comment by lionelB** [comment]
@KnisterPeter Yep I can live with it ;)  I've used ts-emitter on a large codebase (~200files) and have few only error about jsx node but I don't use react on this project :)
<details>
<summary>Jsx related error stack trace</summary>

```
Error: Unknown node kind JsxSelfClosingElement
    at emit (/Users/lionel/Code/client/node_modules/ts-emitter/dist/src/emitter.js:168:11)
    at Object.emitJsxElement (/Users/lionel/Code/client/node_modules/ts-emitter/dist/src/emitter.js:2598:21)
    at emit (/Users/lionel/Code/client/node_modules/ts-emitter/dist/src/emitter.js:166:34)
    at emitJsxElement (/Users/lionel/Code/client/node_modules/ts-emitter/dist/src/emitter.js:2598:21)
    at emitExpression (/Users/lionel/Code/client/node_modules/ts-emitter/dist/src/emitter.js:245:20)
    at emitCallExpression (/Users/lionel/Code/client/node_modules/ts-emitter/dist/src/emitter.js:1733:21)
    at emitExpression (/Users/lionel/Code/client/node_modules/ts-emitter/dist/src/emitter.js:304:20)
    at emitExpressionStatement (/Users/lionel/Code/client/node_modules/ts-emitter/dist/src/emitter.js:1285:17)
    at emitStatement (/Users/lionel/Code/client/node_modules/ts-emitter/dist/src/emitter.js:21:20)
    at node.statements.forEach.statement (/Users/lionel/Code/client/node_modules/ts-emitter/dist/src/emitter.js:1961:21)
```
</details>

The last this wich is annoying is that new inserted code seems to lost context, so there no identation / space (this is the final transform script )

```ts
const ts = require('typescript');

exports.default = (file, api) => {
  const t = api.tscodeshift;
  const ast = t(file.source);

  const props = [];

  ast.find(ts.SyntaxKind.Parameter)
  .filter(p => p.parent.kind === ts.SyntaxKind.Constructor)
  .forEach(p => props.push(ts.createLiteral(`'${p.name.text}'`)));

  if (props.length === 0) {
    return ast.toSource()
  }
  console.log(`${file.path}`)
  props.forEach(p => p.newText = p.text);

  ast.find(ts.SyntaxKind.ClassDeclaration)
    .get(node => node.members)
    .forEach(node => {
      const val = ts.createArrayLiteral(props);

      const prop = ts.createProperty(
          undefined,
          [ts.createKeywordTypeNode(ts.SyntaxKind.StaticKeyword)],
          ' $inject ',
          undefined,
          undefined,
          val
      );

      prop.parent = node.parent;

      prop.getSourceFile = () => {
        return {
          getFullText: () => 'foo'
        };
      };

      node.unshift(prop);
    });

  return ast.toSource();
};

```

**Comment by KnisterPeter** [comment]
Awesome. Sounds really nice. I'm happy this project helped anyone but me :smiley: 

The loss of context in the new code happens, because `ts-emitter` does not have any sense for formatting. All it does is read source to ast, eventually change it, and then write it back with as less changes as possible.
So any new code fragments have no proper formatting.
Could you open issues with some examples so I could have a look at that and build a sane formatting (knowing that it may not everyones cup of tea)?

Regarding the JSX errors: Could you open different issues for that? It would be more easy to track them then.

**Comment by KnisterPeter** [comment]
@lionelB Btw, did you see [tsdi](https://github.com/KnisterPeter/tsdi)? It probably does inject what you want, by using decorators. (This means runtime instead of compile-time though).
