### ISSUE TITLE
Many transforms cause invalid code to be generated

### ISSUE THREAD

**Issue by qix** [KnisterPeter/tscodeshift#25]
Hi there!

Thanks for creating tscodeshift! I'm currently using it to try port a very large code base over to TypeScript and so far it's working really well... for the most part anyway.

I traced down and think I understand the issue. It is somewhat related to #24 but unfortunately sums down to a design flaw in `ts-emitter` that is not easily solvable. The solution I am currently using is a number of hacks[1] that generate valid (though ugly) code... and then pass it through `prettier` to clean it up.

Essentially the problem is the use of source context position in `ts-emitter`. If you do any modification on nodes or any partial modification it creates a situation where `context` no longer accurately reflects the actual position in the source code. The `addWhitespace` function then will add (or not) whitespace based on the wrong location. Usually this is just a styling issue, but in cases such as missing whitespace (`letx = 5;`) or a newline after a return it actually changes the behavior. This also affects the addComma/addSemicolon functions.

I tried to fix it, but unfortunately it seems like a much larger change. One would be to drop the context and instead use `node.getFullStart / node.getStart / etc`... but unfortunately that might make it hard to generate identical source code.

Another option (and preferable for my use case) is if ts-emitter/codeshift could generate syntactically correct source with comments, and then integrate directly into prettier for the formatting.

If you want to see the issues yourself you can run my (reasonably incomplete) js=>ts codeshift on any sufficiently complicated source code.

[1] Pushed hacks at https://github.com/qix/ts-emitter/commit/9ad86b493afe8240b9e05d2b3fb14874c99a2765 for your reference
[2] https://github.com/KnisterPeter/ts-emitter/blob/master/src/utils.ts#L44
[3] https://gist.github.com/qix/393f57cce9994185e2136d50eabcc733

**Comment by KnisterPeter** [comment]
I thanks for your great feedback.
I'm really unhappy to use the context offset internally. But there is no other way that I see to keep almost all code unchanged when reprinting.
There may be a lot of bugs related to that inside `ts-emitter`, but the more general plan with `ts-emitter` is to have the unmodified ast as reference to the original source for reprinting and integrate (during printing not parsing and modifying) it with changes later on.
That way it should have no problems using the source, but I guess right now it is a bit hard to use and changes may have too much influence on the context offset.
Can you create a minimal example and attach that as issue. We could then solve the problems one by one.
