### ISSUE TITLE
Collection.remove() implementation

### ISSUE THREAD

**Issue by blaster151** [KnisterPeter/tscodeshift#26]
I'm looking for a quick way to remove the nodes in a collection from the AST.

For example,
```javascript
root.find(ts.SyntaxKind.CallExpression, { name: 'x' }).remove();
```
I'm coming over from jscodeshift and was excited to find tscodeshift!  If there is another way that I'm missing to remove specific nodes, please let me know.

**Comment by KnisterPeter** [comment]
I think thats api which is missing right now.
Good catch
